### ISSUE TITLE
Invalid EAD export with mixed content note <extref>

### ISSUE THREAD

**Issue by sdm7g** [archivesspace/archivesspace#1087]
When including mixed content with <extref> element in note, ASpace exports EAD with attribute `@href` when `@xlink:href` is required.  `@xlink:type="simple"`  is also required and should probably be added by the serializer.  Should also check if there are similar issues with other linking elements. I expect this is also an issue with EAD3 export.

**Comment by fordmadox** [comment]
The namespace part won't be an issue with EAD3 since EAD3 removed the xlink namespace altogether (i actually miss the namespace, since it seems odd to me to copy the use of xlink but not use the xlink namespace, but that's beside the point :)).  

Also, in case it helps, @sdm7g , Mark Triggs added some sort of "XML cleaning" step to the ASpace Export Service which might help: https://github.com/hudmol/archivesspace_export_service/blob/master/exporter_app/tasks/lib/xml_cleaner.rb  I believe this is the part that fixes any xlink issues during a post-processing step since it's got that NamespaceCorrectingErrorHandler bit.

**Comment by lmcglohon** [comment]
Closing this because fixed with #1655
