### ISSUE TITLE
reports in plugin are found but plugin directories are not in search path for templates. 

### ISSUE THREAD

**Issue by sdm7g** [archivesspace/archivesspace#1111]
A report added to plugins/local/backend/model/reports/  that uses the generic template will be found and work properly, but if it includes and specifies a custom template, the template will not be found. StaticAssetFinder, as called from https://github.com/archivesspace/archivesspace/blob/master/backend/app/lib/reports/report_response.rb#L177 only searches  $base_directory/reports. 
Raises: NotFoundException

**Comment by sdm7g** [comment]
Note that an alternative solution is to just put custom reports and templates into $base_directory/reports, where they both will be found, instead of adding them in plugins.

**Comment by sdm7g** [comment]
https://github.com/archivesspace/archivesspace/pull/1112

**Comment by sdm7g** [comment]
I closed #1112 patch. On further thought, I think the better solution is just to deprecate loading of reports from plugins and to document that they should just be added to  top level reports/ directory. 
( Same instructions for overriding pdf stylesheets/ )

**Comment by mark-cooper** [comment]
@sdm7g I don't always love plugins (especially with Gemfiles in the mix) but as they have to be supported anyway they do have the benefit of being easier to share and deploy than bespoke instructions to do particular things (that's an issue with pdf stylesheets also).

I'm uncomfortable with the talk of "deprecation" because I'm sure there are existing plugins out there that contain reports and nothing should be done to "break" those in my opinion (although I think it would be hard to do that anyway, so perhaps "discourage" is more apt than "deprecate").

@lmcglohon without the patch (and if it's not going forward) perhaps the plugins readme should be updated to point out the limitations of reports added through plugins?

**Comment by lmcglohon** [comment]
Closed because moved to tech-docs repo: https://github.com/archivesspace/tech-docs/issues/17
