### ISSUE TITLE
Deadline for community pull requests for next release: March 16, 2018

### ISSUE THREAD

**Issue by lmcglohon** [archivesspace/archivesspace#1150]
Just a reminder that the deadline by which a pull request needs to be submitted for consideration for the March 2018 release is March 16. Please submit any pull requests no later than the end of your day on March 16. Pull requests submitted after March 16 will be considered for a future release.

(Please note that submitting a pull request by the deadline does not guarantee that it will go into the next release, but it will help ensure that we have adequate time to review and test it before potentially putting it into a release. In general, the pull request deadline is the third Friday of a month in which a release is scheduled, with occasional exceptions when a release is intended to come out earlier in the month.)

If you have any questions, please get in touch. Thanks so much for your contributions and your help in making ArchivesSpace better!

**Comment by bseeger** [comment]
Hello -- can you tell me more about your release process philosophy? This is probably not the best place to ask this question, but I'm not sure where is.

It seems that there are frequent releases and I wonder if you have any recommendations on how often the ArchiveSpace group would expect a user to upgrade to the latest release.   Do you have an idea of which releases your users are using and how often they are upgrading?  

I ask because we have version 1.5.3 installed and if we upgraded to 2.3.1, how long would we want to stay there before upgrading again?  I'm sure the ideal is to mostly keep up with the upgrades, but that takes a bit of time.  That can be challenging if you don't have the staff to devote to it, so I wonder if there are best practices detailed anywhere.   

Thanks,
Bethany

**Comment by cdibella** [comment]
Hi Bethany,

Thanks for your question. (And you're right that this isn't the typical kind of thing we answer here, but happy to do so - feel free to get in touch at ArchivesSpaceHome@lyrasis.org if you have more questions in this vein.) 

In order to get users the functionality and fixes they want from our development backlog faster, we currently ascribe to a philosophy of putting out fairly frequent, smaller releases rather than larger releases at less frequent intervals. Though we've made very significant progress in recent years, there is still a lot that people want from the application, and we want to provide an option for people to have access to additional functionality and improvements as soon as possible. At the same time we don't want to force anyone to have to upgrade ArchivesSpace everytime something new comes out.

We maintain a public roadmap at https://archivesspace.atlassian.net/wiki/spaces/ADC/pages/18710568/Roadmap to give the community a sense of when releases will come out and what will be in them. (We also gave a recent webinar about the roadmap - the recording is up at https://www.youtube.com/watch?v=fuJ5AkD4p2I&feature=youtu.be) One of the ideas behind the roadmap is to provide the information people need to use in the kind of planning you suggest. We do stress that you do not have to make each upgrade, and in most cases you can upgrade from any version of ArchivesSpace to any other version of ArchivesSpace and skip versions in between (when this isn't the case we note it in our release notes and upgrading instructions). We encourage people to use the roadmap to decide which releases are important to them and the best timing for their institution in making upgrades.

Institutional peers will likely have the most relevant ideas on best practices in upgrading, so I'd definitely encourage you to start a discussion on a community listserv if you'd like to get a wider set of views.

Hope that helps. Feel free to get in touch at ArchivesSpaceHome@lyrasis.org with more questions.

Christine
(Program Manager for ArchivesSpace)

**Comment by bseeger** [comment]
Thank you for the information, Christine.
