### ISSUE TITLE
Help understanding the Public UI routes

### ISSUE THREAD

**Issue by cfitz** [archivesspace/archivesspace#1162]
I am going to write some tests for the public UI, but have a lot of questions...to start with the route definitions:
https://github.com/archivesspace/archivesspace/blob/master/public/config/routes.rb

I'm pretty sure a lot of these are not actually being used, specifically all the :get and :post pointing to the same controller action. I'm not seeing the post versions being used.

Also, a lot of the controllers have both #index and  #search actions, but are all those being used? It's a little hard to tell if some of these  #search are really being used at all currently in the code.

Any insights?

**Comment by lmcglohon** [comment]
@cfitz Tackling the tests for the PUI would be great!  I would be surprised if the post actions were used in the PUI - makes no sense because the PUI should be for searching only, therefore no posting required...

As far as having both the index and search actions, I got no clue as to why it was set up that way. Wish I could give you more info on that.

**Comment by cfitz** [comment]
Cool, thx.

I opened a PR ( #1169  ) with some first pass changes...still trying to figure out what's going on, but I do have some code for the public app that follows the selenium stuff ( starts the backend and solr, then runs the rspec tests ). 

Might need to do some reorganziation, especially with how the models, controllers, helpers, views, and concerns are setup?
