### ISSUE TITLE
PUI: "Your request could not be completed due to an unexpected error" message, now appears VERY frequently

### ISSUE THREAD

**Issue by fordmadox** [archivesspace/archivesspace#1213]
Not sure what the cause is, but in the current master branch, this message appears very frequently on the Resource page.  Often it appears when clicking the Inventory tab, and it seems to appear every time if you click on the browser's back button from the Inventory tab.

See:

![request-not-completed-message-appears-quite-frequently](https://user-images.githubusercontent.com/552366/38769729-ab69f7e4-3fd5-11e8-9e76-0f93361bce96.png)

To replicate, go to http://test.archivesspace.org/repositories/12/resources/258, click the Container Inventory tab (at this point the message might show up, but it might not), and then click on the browser's back button.

This also happens in version 2.3.1, as can be seen from here http://sandbox.archivesspace.org/public/repositories/4/resources/22, but I don't see it happening in earlier versions of the new PUI (e.g. 2.1, or 2.2, as far as I can tell)

**Comment by fordmadox** [comment]
And @lmcglohon:  just to follow up on this, I don't see this issue happening in 2.2.2.

**Comment by sdm7g** [comment]
I don't know if it's the same issue, but FWIW, current master https://github.com/archivesspace/archivesspace/commit/96d9243b2148a36d8bd63dcc4e478f6fb2636ebb is also failing for me, both public and frontend.   Investigating...

**Comment by lmcglohon** [comment]
This has a corresponding JIRA ticket: https://archivesspace.atlassian.net/browse/ANW-709

**Comment by cfitz** [comment]
Hey, hm, I did that. 
It's really hard to figure out what's going on with the PUI controllers...but I think the issue was the:
` rescue_from Exception, :with => :render_general_error   `
line in the application controller that I added trying to sort some things out. 
Since it's an issue with Chrome and the back button, I'm going to guess turbolinks is probably caching the page. However, AJAX kicks off a bunch of other requests, some of which get errors, which are resulting in the flash having that message added. JQuery sees that the flash has an error, and updates the cached page. 
:(
I might see if I can get some more hours to write tests for the PUI...
