### ISSUE TITLE
file_version caption has default varchar length in DB despite explict length of text

### ISSUE THREAD

**Issue by pobocks** [archivesspace/archivesspace#1252]
As reported on the listserve, file_version's caption column is limited to 255 chars in the DB, which is short enough that people are running into it.

In the schema, the limit matches the width of TEXT in bytes / 4, which leads me to believe it was intended to be a TEXT column.

My intent is to just reconcile the length to the greater length - if anyone has a positive argument for a "correct" length, let me know and I'll implement that instead.

**Comment by pobocks** [comment]
@lmcglohon I feel like someone should sign off on this before I go and do it, so I'm pinging you to yea/nay or triage?

**Comment by lmcglohon** [comment]
@pobocks I say triage it at the moment.

**Comment by pobocks** [comment]
@lmcglohon I think I misworded that, I meant more, which of these:

1. do this
2. don't do this, it's wrong
3. this should be directed to X person to look at

Does that make sense?

**Comment by lorawoodford** [comment]
This is an oldie, but I believe the primary reason why folks were hitting up against this is because the importer was mapping a digital object title (which can be quite long) to the caption field as well.  This has been changed in #2017 so I suspect this inactive issue can be closed as a result.  Please reopen a new issue if this is not the case.
