### ISSUE TITLE
Error in Rails route loading process

### ISSUE THREAD

**Issue by kardeiz** [archivesspace/archivesspace#1443]
## Expected Behavior

Routes should be eager loaded on app initialization.

## Current Behavior

Routes sometimes get "corrupted" during the initialization process. See https://github.com/rails/rails/issues/23699.

## Possible Solution

Upgrade Rails to latest stable 5.x.

## Steps to Reproduce (for bugs)

It is not really possible to reliably reproduce this bug.

## Context

See https://groups.google.com/forum/#!topic/archivesspace/SYjEZUSa6Nc, which seems to describe the issue we encountered.

## Your Environment

* Version used: 2.4.0

**Comment by lorawoodford** [comment]
HI @kardeiz ~ I've just merged #1953 which includes an update to Rails `5.2.4.3`.  I'm not going to close this issue for now (since it seems niche and hard to replicate), but wanted to make note of the update never the less.  Hopefully, in the future/once a release comes out in a few months' time,  we can confirm your suspicion that this will resolve this issue.
