### ISSUE TITLE
CSV import for container lists

### ISSUE THREAD

**Issue by jronallo** [archivesspace/archivesspace#150]
I created a tool called [Steady](http://steady2.herokuapp.com/) that takes a CSV container list as input and exports EAD XML that could be imported into Archivists' Toolkit and can now be imported into ArchivesSpace. There has been some discussion about adding this functionality into AS itself. In the past the message was that this feature would not be added to AS, though I believe @cfitz has recently suggested on the members' list whether this Steady tool ought to be integrated into AS. (I do not know that much of the [stead](https://github.com/jronallo/stead) code even though Ruby would be very useful.)

Is this CSV container list import a feature that AS would consider implementing in core? When might it happen? Here at NCSU we have considered creating a way for us to do more direct import of CSV into AS, possibly with an application that uses the AS API. If CSV import of container lists is something the core team is going to work on then we can work on some other applications that have AS integrations instead. I would hate to duplicate work. If it is not something AS will be implementing, please let me know so that I can look closer at what it would take to use the AS API to accomplish this.

In any case, I think my experience with creating and administering such a tool could be useful for any development effort. I am happy to help however I can.

**Comment by quoideneuf** [comment]
@jronallo - This sounds good, though I am wondering if it would be necessary to convert the CSV into EAD first. There are already a few [CSV importers](https://github.com/archivesspace/archivesspace/blob/master/backend/app/converters/accession_converter.rb). Would you be interested in writing a plugin that would provide a new converter that accepts Steady-flavored CSV? If so there are few [existing plugins](https://github.com/hudmol/yale_marcxml2accession_extras) you could use as a template.

**Comment by jronallo** [comment]
@quoideneuf Yes, the desire is to avoid converting to EAD XML first and go direct to AS. Though I'd be just as happy if someone else wrote the plugin. :-)

I may look into creating an AS plugin. Is [this tutorial](http://teaspoon-consulting.com/articles/archivesspace-plugins.html) still up to date? What's the development workflow like for creating an AS plugin? How do you write tests for one? Is there an example of a plugin external to core that has tests? The accession converter looks to have tests as it is in the core code, but the yale_marcxml2accession_extras plugin does not apear to have any tests. Can plugins be distributed as gems? If the plugin requires other dependencies how do those get included? I have a lot of questions about plugins, which is why I was considering writing something outside of AS that just used the API and would be a bit more familiar.

**Comment by quoideneuf** [comment]
@jronallo - I'm sorry - I didn't read your first post carefully enough and didn't catch that you were proposing to bypass EAD. Regarding all your questions, I think the answer is "uh...sort of". The tutorial by @marktriggs is the best place to start, and is still up to date. As far as tests go, there's no hook to the core tests as of yet - though we've discussed the need for it. You can of course write your own tests (here's one that does that: [OCLC plugin](https://github.com/hudmol/aspace_oclc)), but currently you can't bootstrap the application and access the ORM, etc., so what you can test is limited. 

If you were starting from scratch I would definitely recommend going the plugin route, especially since there isn't too much overhead to a plugin that just adds a converter, and there are several examples to copy. But since you're not starting from scratch, I can see why you might just want to go the separate app route and work with just the REST API. If you do go the plugin route I'm sure I or someone else will be happy to help if you get stuck - including making changes to core / the plugin API if you hit a roadblock.

Gem distribution would be great and would probably also require a little CLI utility for system administrators, since 'gem install' wouldn't mean much to someone working with a distribution of the application because it bundles everything.

**Comment by marktriggs** [comment]
The work we've been doing lately with Yale to remodel containers has some more extensive tests (that do bootstrap the application + ORM):

  https://github.com/hudmol/yale_containers

Tests under `plugins/[myplugin]/backend/spec/*_spec.rb` get run automatically when you run the usual `build/run backend:test` command against your development checkout.  For example, this one:

  https://github.com/hudmol/yale_containers/blob/master/backend/spec/model_yale_container_spec.rb#L71

creates a test location, then a "Top Container" (our record being tested) that links to that location.  It then verifies that we can get that Top Container out of the DB (by calling `.to_jsonmodel`) and see its location.

The top line:

     require 'spec_helper'

is enough to bootstrap the DB and application for the sake of the test.  Your tests will run against an in-memory DB that has all the ArchivesSpace tables there, and each test runs inside of a transaction that rolls back when it finishes (so the tests are mostly isolated from each other).

**Comment by quoideneuf** [comment]
@marktriggs - not sure now why I thought otherwise, but glad to learn this. Thanks!

**Comment by lmcglohon** [comment]
MArk Triggs says to close this.
