### ISSUE TITLE
Merging controlled values doesn't trigger reindexation of related items

### ISSUE THREAD

**Issue by octomaria** [archivesspace/archivesspace#1622]
Hello,
I'm writing with respect to the problem already reported in JIRA ([ANW-147, 'Merging values "loses" related items?'](https://archivesspace.atlassian.net/browse/ANW-147)).

In the controlled value lists, when merging a value V1 with N1 related items into another value V2 with N2 related items, the expected behavior would be to get V2 with N1 + N2 related items as a result.
The related items are updated correctly, all the items previously related to V1 have their controlled value set to V2.
Yet in the staff interface V2 still shows only N2 related items after the merge.

It seems to me that while the related items are updated, they are not reindexed - and I believe this is the case because their modification time is not changed during the update.
It is intended to be updated in the `migrate` function:
https://github.com/archivesspace/archivesspace/blob/944596e7526f2be2520dc0a3cd59a649e49e2aa2/backend/app/model/enumeration.rb#L45-L49
Yet this definition interferes, I guess:
https://github.com/archivesspace/archivesspace/blob/944596e7526f2be2520dc0a3cd59a649e49e2aa2/common/jsonmodel.rb#L200-L205

At least when I set `readonly` to `false` for `system_mtime`  and then ran a simple merge test, the problem disappeared.
(The same question - of being `readonly` or not - may concern `user_mtime` and `last_modified_by` as well.)

BTW, kudos for all the great work on this project!

**Comment by lorawoodford** [comment]
Related to and, perhaps, partially/fully resolved by #2247 .  @mark-cooper do you think this can be closed?

**Comment by mark-cooper** [comment]
Yeah I think given the work that has be done around this issue since it was reported the situation has improved. There may be some lists that require an update to the underlying model, but those can be zapped as they surface (if any). For the record the problem was: the model being updated may not be a record type that is actually indexed directly in Solr and therefore we need to bump the mtime for the associated record for the count / search to be accurate.
