### ISSUE TITLE
Existence of test and spec directories is confusing

### ISSUE THREAD

**Issue by jeremyf** [archivesspace/archivesspace#1651]
In reviewing the code-base, as a Rails veteran, I found the presence of `test` and `spec` directories a bit confusing.

## Expected Behavior
I would assume a project used either specs or tests. My assumption would be that I would see either one or the other.

## Current Behavior
Both directories exist.

## Possible Solution
Remove the `test` directory from public and front_end as they appear to not be used.

## Context
This affected me as a developer coming to look at the code-base.

## Your Environment
n/a

**Comment by lmcglohon** [comment]
@jeremyf Since this is your first GitHub issue for ArchivesSpace, I would like to invite you to continue to help improve the core code base. I am available to talk with you more about participating or you can check out the resources we have available on our wiki here: https://archivesspace.atlassian.net/wiki/spaces/ADC/overview.
