### ISSUE TITLE
Container image builds take quite a while. Poor layer caching for subsequent builds.

### ISSUE THREAD

**Issue by AustinTSchaffer** [archivesspace/archivesspace#1833]
It takes a long time to build a container image from the Dockerfile and subsequent builds are nearly the same length. The biggest problem that I can see is that Docker has to reinstall all of the dependencies for all of the apps every time anything changes in the repository.

If the build process could be separated so that dependencies are only downloaded and installed whenever the Gemfiles change instead of whenever anything changes, Docker would be able to cache a layer for that step. Then, subsequent builds would be able to reuse the "gems downloaded and installed" layer if the stated dependencies don't change and Docker only need to copy and build the source code.

**Comment by AustinTSchaffer** [comment]
I'm more familiar with the Docker image build process than I am the ArchivesSpace build process, so I apologize if my vocabulary is totally wrong. I've attached the some of the logs from the build process to show which steps shouldn't be affected by changes to the source code and could happen before the source code is copied in to the build container, which would greatly improve the performance of subsequent builds.

[partial_dockerfile_build_log.txt](https://github.com/archivesspace/archivesspace/files/4314826/partial_dockerfile_build_log.txt)

**Comment by mark-cooper** [comment]
Hi @AustinTSchaffer 

Thx for the feedback, and no worries about the vocabulary 😄 

Changing the Docker build to be more inline with general Ruby / Rails best practices such as caching the gems I don't think is possible given the current ArchivesSpace build process.

The Docker image replicates the release process steps (and as such provides a useful layer of testing for the release process):

https://github.com/archivesspace/tech-docs/blob/e030c32c124e855c9ecacfbebdeb2612ff4a2ff6/development/release.md#build-the-release

The build process uses `./scripts/build_release` which calls `./build/run dist` and invokes `bootstrap`, which always resets the gems. I believe an overabundance of caution has been preferred to guarantee a clean slate of gems every time a build is generated. IIRC there
have been issues with multiple gem versions and / or incorrect gem versions being bundled into a release when not starting over in this way (particularly because ArchivesSpace collects gems from multiple Gemfiles).

It's certainly possible that the general build / release process could be reviewed and optimized and is something to look into for the future.

**Comment by AustinTSchaffer** [comment]
@mark-cooper 

Thanks for the response. I briefly looked into the build process and figured that it wouldn't be an easy change, especially since it's all bundled into one command. That interesting using it as a way to test the release process too though, and honestly I'd be ok if we closed this issue just on those grounds.

Maybe we can create a `development.Dockerfile` that prioritizes subsequent build times. Once again, not familiar with how Ruby/Rails builds work so I don't know how easy it would be to just copy the Gemfiles and download everything in them.

Maybe I should just set up a Ruby development environment after all these years of flying blind.
