### ISSUE TITLE
Editing ordered list subnotes with over 2 items corrupts list

### ISSUE THREAD

**Issue by ph448** [archivesspace/archivesspace#1894]
## Expected Behavior
When editing ordered list subnotes we expected to be able to add new items to the list.

## Current Behavior
When adding items to ordered list subnotes with over 2 items we've found that instead of adding the new items ArchivesSpace replaced existing items with the new ones, causing data loss. This seems to only happen on edits, one can create a new ordered list with an arbitrary number of items.

## Steps to Reproduce (for bugs)
1. Create a new ordered list subnote with over 2 items and save it.
2. Edit to add an item and save.
3. Observe that the size of the list did not change and one of the preexisting items has been replaced with the one added in step 2.

## Possible Solution
As ordered list items are stored in a JSON array, this looks to me like an array indexing problem. A quick look at the backend code makes me think the frontend JS is a more likely suspect. The new items seem to fairly consistently get inserted specific points in the list, starting at position 4 for lists over 6 elements long, which made me wonder about  `AS.initTooManySubRecords`, but this is nothing more than a hunch as I can't devote enough time to dig deeper at the moment. 

## Context
One of our archivists found a resource that was supposed to have 41 items in its scope and contents subnote and tried adding the missing ones, only to realise she couldn't. We have advised all our archivists not to edit ordered lists for the moment, but we don't know how many we have managed to corrupt.

## Your Environment
* Version used: v2.7.1
* Environment name and version: Chromium 81.0.4044.122, Firefox 75.0
* Operating System: Linux

**Comment by ph448** [comment]
I've just found a relevant Jira issue (from 2018): [ANW-635 - Editing Ordered Lists - losing data when adding items](https://archivesspace.atlassian.net/browse/ANW-635).

**Comment by lorawoodford** [comment]
Thanks for surfacing this @ph448 .  I did some preliminary investigation and concur that `notes.crud.js` is almost certainly the culprit, as the data-index being set for newly created items does not seem correct/consistent.  I've written up some consistently failing selenium tests, and will be prioritizing this once v2.8 is complete/out.

**Comment by fordmadox** [comment]
@lorawoodford I just started looking at this issue yesterday.  Wowzers.  I think you're spot on about the root cause.  I always get fidgety around CSS class names (and the ever-changing nature of HTML layouts), and I'm not sure exactly how everything is set up in ```notes.crud.js``` but I've got what might pass as a patch available here:  https://github.com/fordmadox/archivesspace/commit/22e55c6cf9b1e9647e052eb6e79a87de102814ca 

This is a really pernicious bug, since it silently deletes existing data.  Hopefully there aren't any others, but I think that these should be categorized separately moving forward if possible.

As for why the counts are off, the tooManyRecords bit could definitely be the reason, @ph448.  If so, it would be better to address there than what I've done.  

Anyhow, some screen shots I took while testing:

Here are things broken, in the sandbox:
<img width="1334" alt="Screen Shot 2020-06-15 at 2 55 26 PM" src="https://user-images.githubusercontent.com/552366/84697750-ae833180-af1c-11ea-9590-5a41f780606b.png">
Note the new lists is starting at position 13, but data-index 13 already exists.

Here are things on my laptop, with that change to the CSS classname for the index variable:
<img width="1321" alt="Screen Shot 2020-06-15 at 2 50 26 PM" src="https://user-images.githubusercontent.com/552366/84697806-c6f34c00-af1c-11ea-86fc-e6843181dc4a.png">
Boom... we're jumping from 9 to 29, but that won't cause an issue once the list is sent to the backend.  The important thing is the next number is not 0-9.

And here I added a few other notes, as well as 101 list items, just to keep on testing to see if I could get things to break:
<img width="1340" alt="Screen Shot 2020-06-15 at 3 04 10 PM" src="https://user-images.githubusercontent.com/552366/84697915-f609bd80-af1c-11ea-9950-5d10312f17f8.png">
Luckily I haven't broken it yet, but it's not really a satisfactory patch, either.  But if it works, I'm leaning toward putting it into production over something that breaks whenever you edit an existing list.

**Comment by mark-cooper** [comment]
@fordmadox I have a branch in testing that approaches this in a more targeted way:

https://github.com/archivesspace/archivesspace/compare/ordered-list-subnotes-fix?expand=1

It would be awesome if you could try it out and let us know if it appears to resolve things for you.

**Comment by fordmadox** [comment]
@mark-cooper looks great, thanks!  I'll give that branch a try tomorrow and let you know.

**Comment by fordmadox** [comment]
@mark-cooper Looks good for the lists.  With the jQuery selector change, the new index number is correct for lists.  

e.g. 

<img width="1575" alt="Screen Shot 2020-06-17 at 11 32 36 AM" src="https://user-images.githubusercontent.com/552366/84918610-d1cdee00-b08e-11ea-8069-1f973f041d02.png">
9, 10, and 11 all coming after 8, as expected 😄 

However, the index for the other notes is still higher than the previous data-index for the note types.  e.g. 

<img width="1578" alt="Screen Shot 2020-06-17 at 11 31 12 AM" src="https://user-images.githubusercontent.com/552366/84918695-f0cc8000-b08e-11ea-86d9-0630cc063e67.png">
Jumping from 5 to 21, since there are a lot of other class names of the same type.

Given that it only matters if there are no duplicate index numbers, I might just keep my current fix in place for now, unless you'd rather we push that to our TEST to test out some more?  

But regardless, I think your fix should go into the core ASAP since it fixes this extremely pernicious bug.  Thanks for digging into this one!!!

**Comment by fordmadox** [comment]
Also, when's ASpace making the leap to Bootstrap 5 and no more jQuery? 😆

**Comment by mark-cooper** [comment]
@fordmadox thx for testing, it's really appreciated! I'll take a look at the higher level note items but in the absence of any reported issues I don't expect that we'll need to make any changes. As for bootstrap 🤐
