### ISSUE TITLE
Staff Interface is not displaying dates properly showing <html> code.

### ISSUE THREAD

**Issue by tpegues2** [archivesspace/archivesspace#2269]
## Expected Behavior

See how the dates field only display "circa 1980-2006".
  | Title | Identifier | Level | Dates | Extent | Actions
-- | -- | -- | -- | -- | -- | --
Selected? | Andrea Gallo Comic Books Collection | RB-11 | Collection | circa 1980-2006

## Current Behavior

We are seeing html code in the Dates column and not just simple dates.   

  | Title | Identifier | Level | Dates | Extent | Actions
-- | -- | -- | -- | -- | -- | --
Selected? | Rare book collections temporary housing | temp | Collection | {"lock_version"=>0, "expression"=>"-", "created_by"=>"admin", "last_modified_by"=>"admin", "create_time"=>"2017-07-21T02:33:34Z", "system_mtime"=>"2017-07-21T02:33:34Z", "user_mtime"=>"2017-07-21T02:33:34Z", "date_type"=>"inclusive", "label"=>"creation", "jsonmodel_type"=>"date"} |   | ViewEdit

## Your Environment

* Version used: 2.8.1 (Recently upgraded to this version from previous release.)
* Environment name and version (e.g. Chrome 39, node.js 5.4): Archivesspace
* Operating System and version (desktop or mobile): RHEL 8.0
* Link to your project:

**Comment by lorawoodford** [comment]
Hi @tpegues2 ,

A reindex will take care of this issue.  Not sure what release you upgraded from, but the release notes for v2.8.0 noted that a full reindex is necessary (https://github.com/archivesspace/archivesspace/releases/tag/v2.8.0).  This was specifically due to the extensive refactoring of the search/browse pages that was included in that release.  

Instructions on completing a full reindex are here: https://archivesspace.github.io/tech-docs/administration/indexes.html
