### ISSUE TITLE
Unitids have their content rewritten.

### ISSUE THREAD

**Issue by pobocks** [archivesspace/archivesspace#328]
For reasons that are not recorded in the source, unitid content in archival objects have the following transformation applied to them on EAD conversion:

```Ruby
inner_xml.gsub(/[\/_\-.]/, '_')
```
This happens here:

https://github.com/archivesspace/archivesspace/blob/master/backend/app/converters/ead_converter.rb#L137

As far as I know, all of the replaced characters are perfectly legal within unitid elements, and in fact dashes are used in the LOC example.

**Comment by cfitz** [comment]
Hi, yes, that is odd. I think because when a resource has a unit_id, it gets applied as the first part of resource's identifier ( id_0 ) which needs to be normalized. But for archival_objects, it gets put into the component id field, which is just text.

I think it would be safe to have this not normalized...if you want to send a pull request, maybe add some tests to make sure this validates to the json schema.
